# Generated by Django 3.0.5 on 2020-05-10 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=200, verbose_name='Case Name')),
                ('test_result', models.BooleanField(verbose_name='Test Result')),
                ('tester', models.CharField(max_length=32, verbose_name='Tester')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': 'App Testing Case',
                'verbose_name_plural': 'App Testing Case',
            },
        ),
        migrations.CreateModel(
            name='AppCaseStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_step', models.CharField(max_length=200, verbose_name='Test Step')),
                ('test_object_name', models.CharField(max_length=200, verbose_name='測試對象名稱')),
                ('find_method', models.CharField(max_length=200, verbose_name='定位方式')),
                ('ev_element', models.CharField(max_length=800, verbose_name='控件元素')),
                ('operate_method', models.CharField(max_length=200, verbose_name='操作方法')),
                ('test_data', models.CharField(max_length=200, null=True, verbose_name='測試數據')),
                ('assert_data', models.CharField(max_length=200, verbose_name='驗證數據')),
                ('test_result', models.BooleanField(verbose_name='Pass')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
                ('app_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptest.AppCase')),
            ],
        ),
    ]
