# Generated by Django 3.0.5 on 2020-05-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=64, verbose_name='Product Name')),
                ('product_desc', models.CharField(max_length=512, verbose_name='Product Description')),
                ('product_admin', models.CharField(max_length=64, verbose_name='Product Administrator')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
            ],
            options={
                'verbose_name': 'Product Manage',
                'verbose_name_plural': 'Product Manage',
            },
        ),
    ]
