# Generated by Django 3.0.5 on 2020-05-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=512)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=32)),
                ('c_time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'username',
                'verbose_name_plural': 'username',
                'ordering': ['c_time'],
            },
        ),
    ]
