# Generated by Django 3.0.7 on 2020-07-01 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webCaseName', models.CharField(max_length=200, verbose_name='測試用例名稱')),
                ('webTestResult', models.BooleanField(verbose_name='測試結果')),
                ('tester', models.CharField(max_length=16, verbose_name='Tester')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': 'Web Test Case',
                'verbose_name_plural': 'Web Test Case',
            },
        ),
        migrations.CreateModel(
            name='WebCaseStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webCaseName', models.CharField(max_length=200, verbose_name='測試用例標題')),
                ('webStep', models.CharField(max_length=200, verbose_name='測試步驟')),
                ('webObjName', models.CharField(max_length=200, verbose_name='測試對象名稱')),
                ('webFindMethod', models.CharField(max_length=200, verbose_name='定位方式')),
                ('webElement', models.CharField(max_length=200, verbose_name='控件元素')),
                ('webOptMethod', models.CharField(max_length=200, verbose_name='操作方法')),
                ('webTestData', models.CharField(max_length=200, null=True, verbose_name='測試數據')),
                ('webAssertData', models.CharField(max_length=200, verbose_name='驗證數據')),
                ('webTestResult', models.BooleanField(verbose_name='測試結果')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
                ('webcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.WebCase')),
            ],
        ),
    ]
