# Generated by Django 3.0.5 on 2020-05-08 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_test_name', models.CharField(max_length=64, verbose_name='API Name')),
                ('api_tester', models.CharField(max_length=64, verbose_name='Tester')),
                ('apt_test_result', models.BooleanField(verbose_name='Testing Result')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
            ],
        ),
        migrations.CreateModel(
            name='ApiStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_step', models.CharField(max_length=100, null=True, verbose_name='Step')),
                ('api_name', models.CharField(max_length=100, verbose_name='Name')),
                ('api_url', models.CharField(max_length=200, verbose_name='Url')),
                ('api_param_value', models.CharField(max_length=800, verbose_name='Param_Value')),
                ('api_method', models.CharField(max_length=100, verbose_name='Method')),
                ('api_result', models.CharField(max_length=200, verbose_name='Result')),
                ('api_status', models.BooleanField(verbose_name='Status')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
                ('ApiTest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.ApiTest')),
            ],
        ),
    ]
