# Generated by Django 3.0.5 on 2020-05-08 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitest',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='apitest',
            name='api_test_desc',
            field=models.CharField(max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='api_method',
            field=models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], default='GET', max_length=100, null=True, verbose_name='Method'),
        ),
        migrations.AlterField(
            model_name='apitest',
            name='api_test_name',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='apitest',
            name='apt_test_result',
            field=models.BooleanField(verbose_name='Result'),
        ),
    ]
