# Generated by Django 3.0.5 on 2020-05-10 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('apitest', '0003_apitest_apistep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100, verbose_name='API Name')),
                ('api_url', models.CharField(max_length=200, verbose_name='API Url')),
                ('apt_param_value', models.CharField(max_length=800, verbose_name='Param_Value')),
                ('api_method', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], default='GET', max_length=200, verbose_name='Request Method')),
                ('api_result', models.CharField(max_length=200, verbose_name='API RESULT')),
                ('api_status', models.BooleanField(verbose_name='Pass')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': '單一場景接口',
                'verbose_name_plural': '單一場景接口',
            },
        ),
    ]
