# Generated by Django 3.0.5 on 2020-05-10 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_name', models.CharField(max_length=64, verbose_name='Bug Name')),
                ('bug_detail', models.CharField(max_length=200, verbose_name='Details')),
                ('bug_status', models.CharField(choices=[('Active', 'Active'), ('Solved', 'Solved'), ('Closed', 'Closed')], default='Active', max_length=200, null=True, verbose_name='Status')),
                ('bug_level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='3', max_length=200, null=True, verbose_name='Bug Revel')),
                ('bug_creater', models.CharField(max_length=200, verbose_name='創建人')),
                ('bug_assign', models.CharField(max_length=200, verbose_name='分配給')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': 'Bug Management',
            },
        ),
    ]
